name = "HijuepapusCraft"
author = "juanloaiza21"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "266888a8ebe23b55a9b37bdb757c1e502b1c28ecd8e76f523034410c7f271727"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
