name = "HijuepapusCraft"
author = "juanloaiza21"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "763d5c45d51d27e1a67c2bbb1260ecf4597e8b3779dd5697be1baa2343e3c9e1"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
