name = "HijuepapusCraft"
author = "juanloaiza21"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c052c5d3fb0143369b89b943cbefc450b104293cebae866f7f8b0f0e66e54d2a"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
